### ISSUE TITLE
Downloading of vWii system titles not working

### ISSUE THREAD

**Issue by curtisy1** [ihaveamac/wiiu-things#2]
Downloading vWii system titles results in an error in line 90. Following error message is provided:

    line 90, in <module>
        struct.unpack(">H", tmd[0xB0A + (0x30 * c):0xB0A + (0x30 * c) + 0x2])[0],
    struct.error: unpack requires a bytes object of length 2

Any idea on how to fix this or how I could fetch vWii Sysmenu for testing some RedNAND stuff?

**Comment by ihaveamac** [comment]
Wii/vWii titles use a different tmd format than Wii U(which uses the same format as 3DS), so the offsets for everything are different. I suggest using nustool by SciresM in the mean time.

**Comment by curtisy1** [comment]
I see. Thanks for the suggestion! Unfortunately nustool doesn't seem to be
able to decrypt downloaded vWii files by default, but that's another story.

Many thanks for your help!

**Comment by ihaveamac** [comment]
Wii/vWii nus titles should be relatively easy to decrypt like any other system (decrypt titlekey with vWii common, decrypt contents, assuming you know the process)

**Comment by curtisy1** [comment]
Yeah, I think I have it working now. Thanks for the help, you're awesome!
